[package]
name = "gst-plugin-threadshare"
version = "0.1.0"
authors = ["Sebastian Dröge <sebastian@centricular.com>"]
license = "LGPL-2.1+"

[dependencies]
glib = { git = "https://github.com/gtk-rs/glib" }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs" }
gst-plugin = { git = "https://github.com/sdroege/gst-plugin-rs" }
tokio = { git = "https://github.com/tokio-rs/tokio" }
tokio-reactor = { git = "https://github.com/tokio-rs/tokio" }
tokio-executor = { git = "https://github.com/tokio-rs/tokio" }
futures = "0.1"
lazy_static = "1.0"
either = "1.0"

[lib]
name = "gstthreadshare"
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = true
opt-level = 3
debug = true
panic = 'unwind'
